products_details = [
    ['Portable Charger', 'Never run out of battery again with this portable charger. Compatible with most devices.',
     200, 'A3'],
    ['Smart Lock', 'Secure your home with this smart lock. Offers keyless entry and remote control.', 15, 'B1'],
    ['Smart Thermostat',
     "Save energy and control your home's temperature with this smart thermostat. Compatible with most HVAC systems.",
     20, 'A1'],
    ['Smartwatch',
     'Stay connected and on top of your daily tasks with this smartwatch. Features include notifications.', 75, 'B1'],
    ['Noise-Cancelling Headphones',
     'Block out external noise and enjoy high-quality sound with these noise-cancelling headphones.', 30, 'B2'],
    ['Gaming Keyboard',
     'Get the edge in your gaming with this backlit keyboard. Features programmable keys and customizable lighting.',
     25, 'D1'],
    ['Wireless Keyboard',
     'Type comfortably and wirelessly with this full-sized keyboard. Offers quiet and responsive keys.', 80, 'B2'],
    ['Bluetooth Speaker',
     'Listen to music anywhere with this portable Bluetooth speaker. Offers high-quality sound and long battery life.',
     100, 'B3'],
    ['Wireless Earbuds',
     'Enjoy music without wires with these Bluetooth-enabled earbuds. Comes with a charging case for convenience.', 100,
     'A1'],
    ['Wireless Mouse',
     'Eliminate the clutter of cords with this wireless mouse. Offers precise movement and comfortable grip.', 150,
     'C1'],
    ['USB Flash Drive', 'Store and transfer files easily with this USB flash drive. Compact and durable design.', 250,
     'C2'],
    ['Wireless Charger',
     'Charge your phone quickly and wirelessly with this charging pad. Compatible with most devices.', 200, 'A2'],
    ['External Hard Drive',
     'Keep all your important files in one place with this external hard drive. Offers high-capacity storage and fast data transfer speeds.',
     50, 'C3'],
    ['Wireless Router',
     'Get fast and reliable internet with this wireless router. Offers strong Wi-Fi signal and easy setup.', 40, 'D3'],
    ['Smart Plug',
     'Control your home appliances with this smart plug. Works with voice assistants and features scheduling and remote control.',
     100, 'B2'],
    ['Bluetooth Headset',
     'Take calls hands-free with this Bluetooth headset. Offers long battery life and noise-cancelling technology.', 60,
     'C1'],
    ['Fitness Tracker',
     'Keep track of your daily activity with this sleek fitness tracker. Monitors steps calories burned and heart rate.',
     50, 'A2'],
    ['Wireless Printer',
     'Print from anywhere with this wireless printer. Offers fast printing speeds and high-quality output.', 20, 'D3'],
    ['Webcam',
     'Stay connected with friends and colleagues with this high-definition webcam. Compatible with most video conferencing apps.',
     80, 'D2'],
    ['Security Camera',
     'Keep an eye on your home or business with this high-definition security camera. Features motion detection and remote viewing.',
     30, 'C3'],
    ['Bluetooth Earbuds',
     'Listen to music on the go with these Bluetooth earbuds. Offers comfortable fit and long battery life.', 120, 'A3']
]

employees_details = [
    ['012457890', 'Yosi', 'Lev', 'shalom 41/4 Tel-Avive', '054-6369912', 'M'],
    ['123456789', 'Yael', 'Revivo', 'ezel 1/2 Ramat-gan', '050-3696912', 'F'],
    ['213697458', 'Tom', 'Lahav', 'Yosef 22/2 Givatiim', '052-1263645', 'M'],
    ['582971364', 'Mor', 'Shalom', 'Herzel 115/6 Holon', '054-6926391', 'F'],
]

